import * as z from "zod";

const baseProductSchema = z.object({
  name: z.string().min(1, "Name is required"),
  brand: z.string().min(1, "Brand is required"),
  model_name: z.string().min(1, "Model name is required"),
  price: z.number().min(0, "Price must be positive"),
  display_specs: z.string().min(1, "Display specifications are required"),
  processor: z.string().min(1, "Processor is required"),
  ram: z.string().min(1, "RAM is required"),
  storage: z.string().min(1, "Storage is required"),
  battery: z.string().min(1, "Battery specifications are required"),
  os: z.string().min(1, "Operating system is required"),
  color: z.string().min(1, "Color is required"),
  buy_link: z.string().url("Please enter a valid URL").optional().nullable(),
  image_url: z.string().optional(),
  gallery_images: z.array(z.string()).optional(),
});

export const laptopProductSchema = baseProductSchema.extend({
  series: z.string().min(1, "Series is required"),
  thickness: z.string().min(1, "Thickness is required"),
  dimensions: z.string().min(1, "Dimensions are required"),
  weight: z.string().min(1, "Weight is required"),
  os_type: z.string().min(1, "OS type is required"),
  display_size: z.string().min(1, "Display size is required"),
  display_resolution: z.string().min(1, "Display resolution is required"),
  pixel_density: z.string().min(1, "Pixel density is required"),
  display_features: z.string().min(1, "Display features are required"),
  refresh_rate: z.string().min(1, "Refresh rate is required"),
  graphics: z.string().min(1, "Graphics is required"),
  graphics_memory: z.string().min(1, "Graphics memory is required"),
  clock_speed: z.string().min(1, "Clock speed is required"),
  cache: z.string().min(1, "Cache is required"),
  ram_type: z.string().min(1, "RAM type is required"),
  ram_speed: z.string().min(1, "RAM speed is required"),
  memory_slots: z.string().min(1, "Memory slots are required"),
  expandable_memory: z.string().min(1, "Expandable memory is required"),
  ssd_capacity: z.string().min(1, "SSD capacity is required"),
  battery_cell: z.string().min(1, "Battery cell is required"),
  battery_type: z.string().min(1, "Battery type is required"),
  power_supply: z.string().min(1, "Power supply is required"),
  battery_life: z.string().min(1, "Battery life is required"),
  wlan: z.string().min(1, "WLAN is required"),
  wifi_version: z.string().min(1, "Wi-Fi version is required"),
  bluetooth_version: z.string().min(1, "Bluetooth version is required"),
  hdmi_ports: z.string().min(1, "HDMI ports are required"),
  usb_type_c: z.string().min(1, "USB Type-C is required"),
  ethernet_ports: z.string().min(1, "Ethernet ports are required"),
  headphone_jack: z.boolean(),
  microphone_jack: z.boolean(),
  webcam: z.boolean(),
  video_recording: z.string().min(1, "Video recording is required"),
  audio_solution: z.string().min(1, "Audio solution is required"),
  microphone: z.boolean(),
  backlit_keyboard: z.string().min(1, "Backlit keyboard is required"),
  face_recognition: z.string().min(1, "Face recognition is required"),
  warranty: z.string().min(1, "Warranty is required"),
  sales_package: z.string().min(1, "Sales package is required"),
});

export const mobileProductSchema = baseProductSchema.extend({
  camera: z.string().min(1, "Camera specifications are required"),
  chipset: z.string().optional(),
  charging_specs: z.string().optional(),
  resolution: z.string().optional(),
  screen_size: z.string().optional(),
  announced: z.string().optional(),
  status: z.string().optional(),
  cpu_details: z.string().optional(),
  gpu_details: z.string().optional(),
  card_slot: z.boolean().optional(),
  memory_type: z.string().optional(),
  display_type: z.string().optional(),
  display_protection: z.string().optional(),
  dimensions: z.string().optional(),
  weight: z.string().optional(),
  build_material: z.string().optional(),
  sim_type: z.string().optional(),
  protection_rating: z.string().optional(),
  wlan: z.string().optional(),
  bluetooth: z.string().optional(),
  nfc: z.boolean().optional(),
  gps: z.string().optional(),
  usb_type: z.string().optional(),
  radio: z.boolean().optional(),
  infrared: z.boolean().optional(),
  network_technology: z.string().optional(),
  network_speed: z.string().optional(),
  loudspeaker_type: z.string().optional(),
  audio_jack: z.boolean().optional(),
  sensors: z.array(z.string()).optional(),
  available_colors: z.array(z.string()).optional(),
  model_variants: z.array(z.string()).optional(),
  bands_2g: z.array(z.string()).optional(),
  bands_3g: z.array(z.string()).optional(),
  bands_4g: z.array(z.string()).optional(),
  bands_5g: z.array(z.string()).optional(),
});

// Create update schemas where all fields are optional
export const mobileProductUpdateSchema = mobileProductSchema.partial();
export const laptopProductUpdateSchema = laptopProductSchema.partial();

export type ProductFormData = z.infer<typeof mobileProductSchema> | z.infer<typeof laptopProductSchema>;
export type ProductUpdateData = z.infer<typeof mobileProductUpdateSchema> | z.infer<typeof laptopProductUpdateSchema>;
export type ExpertReviewFormData = z.infer<typeof expertReviewSchema>;

export const expertReviewSchema = z.object({
  rating: z.number().min(0).max(10),
  author: z.string().min(1, "Author is required"),
  summary: z.string().min(1, "Summary is required"),
  detailed_review: z.string().optional(),
  pros: z.array(z.string()).min(1, "At least one pro is required"),
  cons: z.array(z.string()).min(1, "At least one con is required"),
  verdict: z.string().min(1, "Verdict is required"),
});